Modified style.css,index.html and index.js file
nisha331/flow_cycle1 pull request #56
Opened 2023-02-21 19:10 UTC by vk20july

Mam Please Review my code

2023-02-22 14:34 UTC, devvsakib requested changes
also replace let/const instead var.

2023-02-22 14:34 UTC, devvsakib commented on js_files/index.js
> +  console.log(calender1);
delete all console log code from the file. It's not a good practice to put console code

2023-02-22 16:49 UTC, vk20july commented
ok sir

2023-02-22 16:55 UTC, vk20july commented
@devvsakib sir made the changes please review

2023-02-23 09:33 UTC, devvsakib requested changes
I actually said to use let or const without using var. I didn't mean to use var variable.

Line 8 use const.
Lines 24 to 31 replace var with let.

2023-02-23 09:57 UTC, nisha331 commented
@vk20july can i have the screenrecoding of the task

2023-02-23 10:01 UTC, devvsakib commented
> @vk20july can i have the screenrecoding of the task.. So i can see if things are working fine

you can add vercel to this project, so when someone makes PR, vercel will automatically deploy your site, and give a preview before merging.

2023-02-23 10:07 UTC, nisha331 commented
> > @vk20july can i have the screenrecoding of the task.. So i can see if things are working fine
> 
> you can add vercel to this project, so when someone makes PR, vercel will automatically deploy your site, and give a preview before merging.

yeah will do  that for the moment he can just give the screenrecording

2023-02-23 10:12 UTC, vk20july commented
Ok @nisha331 @devvsakib will create proper pull request by tonight

2023-02-23 13:27 UTC, vk20july commented
https://user-images.githubusercontent.com/71543332/220919966-60bd09e4-3139-4987-bca6-b652245304b3.mp4

2023-02-23 13:28 UTC, vk20july commented
@nisha331 @devvsakib kindly review the changes

2023-02-23 18:48 UTC, nisha331 approved these changes

2023-02-23 18:48 UTC, merged